# Generated by Django 5.0.7 on 2025-01-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdolQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthplace', models.CharField(max_length=255)),
                ('zodiac', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
            ],
        ),
    ]
