# Generated by Django 5.0.7 on 2025-01-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdolQuiz',
        ),
    ]
