# Generated by Django 5.0.7 on 2025-01-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idolize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoldatabase',
            name='birthdate',
            field=models.CharField(max_length=50),
        ),
    ]
