# Generated by Django 5.0.7 on 2025-02-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idolize', '0003_alter_idoldatabase_idol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoldatabase',
            name='sns',
            field=models.JSONField(default=list),
        ),
    ]
